networks:
  mysql-ha:
    driver: bridge

services:
  mysql:
    image: manageitwa/mysql-ha-cloud:dev
    build: .
    environment:
      CONSUL_BOOTSTRAP_SERVER: mysql
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_ENABLE_UI: "true"
      CONSUL_BOOTSTRAP_EXPECT: 3

      # Obviously, don't use these in production
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: application
      MYSQL_USER: application_user
      MYSQL_PASSWORD: application_pass

      MYSQL_BACKUP_USER: backup_user
      MYSQL_BACKUP_PASSWORD: backup_pass

      MYSQL_REPLICATION_USER: replication_user
      MYSQL_REPLICATION_PASSWORD: replication_pass
    networks:
      - mysql-ha
    volumes:
      - ./snapshots:/snapshots
      - ./mysql_cluster_manager/src/mcm:/cluster/mcm
      - ./mysql_cluster_manager/src/mysql_cluster_manager.py:/cluster/mysql_cluster_manager.py
      - ./entrypoint.sh:/cluster/entrypoint.sh
    deploy:
      replicas: 3
    ports:
      - 8300
      - 8301/tcp
      - 8301/udp
      - 8302/tcp
      - 8302/udp
      - 8500
      - 8501
      - 8502
      - 8503
      - 8600/tcp
      - 8600/udp
      - 6032
      - 6033
