networks:
  mysql-ha:
    driver: overlay

services:
  mysql:
    image: manageitwa/mysql-ha-cloud:dev
    build: .
    environment:
      CONSUL_BOOTSTRAP_SERVICE: mysql
      CONSUL_BOOTSTRAP_EXPECT: 3
      CONSUL_ENABLE_UI: "true"

      # Obviously, don't use these in production
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: application
      MYSQL_USER: application_user
      MYSQL_PASSWORD: application_pass

      MYSQL_BACKUP_USER: backup_user
      MYSQL_BACKUP_PASSWORD: backup_pass

      MYSQL_REPLICATION_USER: replication_user
      MYSQL_REPLICATION_PASSWORD: replication_pass
    networks:
      mysql-ha:
    volumes:
      - ./snapshots:/snapshots
      - ./mysql_cluster_manager/src/mcm:/cluster/mcm
      - ./mysql_cluster_manager/src/mysql_cluster_manager.py:/cluster/mysql_cluster_manager.py
      - ./entrypoint.sh:/cluster/entrypoint.sh
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
    ports:
      - 6033:6032
      - 3306:6033
