"""
This type stub file was generated by pyright.
"""

from consul.check import Check
from consul.exceptions import ACLDisabled, ACLPermissionDenied, ConsulException, NotFound, Timeout
from consul.std import Consul

__version__ = ...
