"""
This type stub file was generated by pyright.
"""

from typing import Optional
from consul import base

__all__ = ["Consul"]
class HTTPClient(base.HTTPClient):
    """Asyncio adapter for python consul using aiohttp library"""
    def __init__(self, *args, loop=..., connections_limit=..., connections_timeout=..., **kwargs) -> None:
        ...
    
    def get(self, callback, path, params=..., headers: Optional[dict[str, str]] = ..., connections_timeout=...) -> CoroutineType[Any, Any, Any]:
        ...
    
    def put(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ..., connections_timeout=...) -> CoroutineType[Any, Any, Any]:
        ...
    
    def delete(self, callback, path, params=..., headers: Optional[dict[str, str]] = ..., connections_timeout=...) -> CoroutineType[Any, Any, Any]:
        ...
    
    def post(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ..., connections_timeout=...) -> CoroutineType[Any, Any, Any]:
        ...
    
    def close(self):
        ...
    


class Consul(base.Consul):
    def __init__(self, *args, loop=..., connections_limit=..., connections_timeout=..., **kwargs) -> None:
        ...
    
    def http_connect(self, host: str, port: int, scheme, verify: bool = ..., cert=...) -> HTTPClient:
        ...
    
    def close(self):
        """Close all opened http connections"""
        ...
    


