"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any, Optional, TYPE_CHECKING
from types import TracebackType

if TYPE_CHECKING:
    ...
log = ...
Response = ...
class HTTPClient(metaclass=abc.ABCMeta):
    def __init__(self, host: str = ..., port: int = ..., scheme: str = ..., verify: bool = ..., cert=...) -> None:
        ...
    
    def uri(self, path: str, params: list[tuple[str, Any]] | None = ...) -> str:
        ...
    
    @abc.abstractmethod
    def get(self, callback, path, params=..., headers: Optional[dict[str, str]] = ...):
        ...
    
    @abc.abstractmethod
    def put(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ...):
        ...
    
    @abc.abstractmethod
    def delete(self, callback, path, params=..., headers: Optional[dict[str, str]] = ...):
        ...
    
    @abc.abstractmethod
    def post(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ...):
        ...
    
    @abc.abstractmethod
    def close(self):
        ...
    


class Consul:
    def __init__(self, host: str | None = ..., port: int | None = ..., token: str | None = ..., scheme: str | None = ..., consistency: str = ..., dc=..., verify: bool | None = ..., cert=...) -> None:
        """
        *token* is an optional `ACL token`_. If supplied it will be used by
        default for all requests made with this client session. It's still
        possible to override this token by passing a token explicitly for a
        request.

        *consistency* sets the consistency mode to use by default for all reads
        that support the consistency option. It's still possible to override
        this by passing explicitly for a given request. *consistency* can be
        either 'default', 'consistent' or 'stale'.

        *dc* is the datacenter that this agent will communicate with.
        By default the datacenter of the host is used.

        *verify* is whether to verify the SSL certificate for HTTPS requests

        *cert* client side certificates for HTTPS requests
        """
        ...
    
    def __enter__(self) -> Self:
        ...
    
    async def __aenter__(self) -> Self:
        ...
    
    def __exit__(self, exc_type: Optional[type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]) -> None:
        ...
    
    async def __aexit__(self, exc_type: Optional[type[BaseException]], exc: Optional[BaseException], tb: Optional[TracebackType]) -> None:
        ...
    
    @abc.abstractmethod
    def http_connect(self, host: str, port: int, scheme, verify: bool = ..., cert=...) -> None:
        ...
    
    def prepare_headers(self, token: Optional[str] = ...) -> dict[str, str]:
        ...
    


