"""
This type stub file was generated by pyright.
"""

from typing import Callable, TYPE_CHECKING
from consul.base import Response

if TYPE_CHECKING:
    ...
class CB:
    @classmethod
    def boolean(cls) -> Callable[[Response], bool]:
        ...
    
    @classmethod
    def json(cls, postprocess=..., allow_404: bool = ..., one: bool = ..., decode: bool | str = ..., is_id: bool = ..., index: bool = ...) -> Callable[..., tuple[Any, Any | None] | Any | None]:
        """
        *postprocess* is a function to apply to the final result.

        *allow_404* if set, None will be returned on 404, instead of raising
        NotFound.

        *index* if set, a tuple of index, data will be returned.

        *one* returns only the first item of the list of items. empty lists are
        coerced to None.

        *decode* if specified this key will be base64 decoded.

        *is_id* only the 'ID' field of the json object will be returned.
        """
        ...
    


