"""
This type stub file was generated by pyright.
"""

from typing import Any

log = ...
class Check:
    """
    There are three different kinds of checks: script, http and ttl
    """
    @classmethod
    def script(cls, args, interval, deregister=...) -> dict[str, Any]:
        """
        Run the script *args* every *interval* (e.g. "10s") to peform health
        check
        """
        ...
    
    @classmethod
    def http(cls, url, interval, timeout=..., deregister=..., header=...) -> dict[str, Any]:
        """
        Peform a HTTP GET against *url* every *interval* (e.g. "10s") to peform
        health check with an optional *timeout* and optional *deregister* after
        which a failing service will be automatically deregistered. Optional
        parameter *header* specifies headers sent in HTTP request. *header*
        paramater is in form of map of lists of strings,
        e.g. {"x-foo": ["bar", "baz"]}.
        """
        ...
    
    @classmethod
    def tcp(cls, host: str, port: int, interval, timeout=..., deregister=...) -> dict[str, Any]:
        """
        Attempt to establish a tcp connection to the specified *host* and
        *port* at a specified *interval* with optional *timeout* and optional
        *deregister* after which a failing service will be automatically
        deregistered.
        """
        ...
    
    @classmethod
    def ttl(cls, ttl: str) -> dict[str, Any]:
        """
        Set check to be marked as critical after *ttl* (e.g. "10s") unless the
        check is periodically marked as passing.
        """
        ...
    
    @classmethod
    def docker(cls, container_id, shell, script, interval, deregister=...) -> dict[str, Any]:
        """
        Invoke *script* packaged within a running docker container with
        *container_id* at a specified *interval* on the configured
        *shell* using the Docker Exec API.  Optional *register* after which a
        failing service will be automatically deregistered.
        """
        ...
    


