"""
This type stub file was generated by pyright.
"""

class ConsulException(Exception):
    ...


class ACLDisabled(ConsulException):
    ...


class ACLPermissionDenied(ConsulException):
    ...


class NotFound(ConsulException):
    ...


class Timeout(ConsulException):
    ...


class BadRequest(ConsulException):
    ...


class ClientError(ConsulException):
    """Encapsulates 4xx Http error code"""
    ...


