"""
This type stub file was generated by pyright.
"""

from typing import Optional
from requests import Response
from consul import base

__all__ = ["Consul"]
class HTTPClient(base.HTTPClient):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def response(self, response: Response) -> Response:
        ...
    
    def get(self, callback, path, params=..., headers: Optional[dict[str, str]] = ...):
        ...
    
    def put(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ...):
        ...
    
    def delete(self, callback, path, params=..., headers: Optional[dict[str, str]] = ...):
        ...
    
    def post(self, callback, path, params=..., data: str = ..., headers: Optional[dict[str, str]] = ...):
        ...
    
    def close(self) -> None:
        ...
    


class Consul(base.Consul):
    def http_connect(self, host: str, port: int, scheme, verify: bool = ..., cert=...) -> HTTPClient:
        ...
    


