name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
          FORGEJO_URL: https://source.selfmanager.net.au
          FORGEJO_TOKEN: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
          REPOSITORY: ${{ forgejo.repository }}
          WORKFLOW_FILE: build-image.yml
        run: npx --package semantic-release --package @semantic-release/exec --package @ribbon-studios/semantic-release-forgejo semantic-release
