"""
This type stub file was generated by pyright.
"""

from consul.api.acl.policy import Policy
from consul.api.acl.token import Token

class ACL:
    def __init__(self, agent) -> None:
        ...
    


