"""
This type stub file was generated by pyright.
"""

from typing import Optional

class Policy:
    def __init__(self, agent) -> None:
        ...
    
    def list(self, token: str | None = ...):
        """
        Lists all the active ACL policies. This is a privileged endpoint, and
        requires a management token. *token* will override this client's
        default token.
        Requires a token with acl:read capability. ACLPermissionDenied raised otherwise
        """
        ...
    
    def read(self, uuid, token: str | None = ...):
        """
        Returns the policy information for *id*. Requires a token with acl:read capability.
        :param uuid: Specifies the UUID of the policy you look up.
        :param token: token with acl:read capability
        :return: selected Polic information
        """
        ...
    
    def create(self, name: str, token: str | None = ..., description: Optional[str] = ..., rules=...):
        """
        Create a policy
        This is a privileged endpoint, and requires a token with acl:write.
        :param name: Specifies a name for the ACL policy.
        :param token: token with acl:write capability
        :param description: Free form human-readable description of the policy.
        :param rules: Specifies rules for the ACL policy.
        :return: The cloned token information
        """
        ...
    


