"""
This type stub file was generated by pyright.
"""

class Connect:
    def __init__(self, agent) -> None:
        ...
    
    class CA:
        def __init__(self, agent) -> None:
            ...
        
        def roots(self, pem: bool = ..., token: str | None = ...):
            ...
        
        def configuration(self, token: str | None = ...):
            ...
        
    
    


