"""
This type stub file was generated by pyright.
"""

class Operator:
    def __init__(self, agent) -> None:
        ...
    
    def raft_config(self):
        """
        Returns raft configuration.
        """
        ...
    


